#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean 
wclean fvMotionSolvers
wclean thermophysicalModels
wclean functionObjects
wclean functionObjects/field

# ----------------------------------------------------------------- end-of-file
