#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wmake dep 
wmake libso 
wmake libso fvMotionSolvers
wmake libso thermophysicalModels
wmake libso functionObjects
wmake libso functionObjects/field
# ----------------------------------------------------------------- end-of-file
