#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean myDbns
wclean myLusgsFoam

wclean mySonicLiquidFoam
wclean myRhoSimpleFoam

# ----------------------------------------------------------------- end-of-file
