#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wmake libso myDbns
wmake myLusgsFoam
wmake myLusgsFoam/myLusgsDyMFoam

# ----------------------------------------------------------------- end-of-file
