#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean myDbns
wclean myLusgsFoam
wclean myLusgsFoam/myLusgsDyMFoam

wclean mySonicLiquidFoam

# ----------------------------------------------------------------- end-of-file
